hello-image:
	docker build . -t hello-rob
	docker build . -t hello-rob:v1.0.0

hello-run:
	docker run --name robs-hello hello-rob

greetingsjs-image:
	docker build . -t greetings-js -f ./Dockerfile.greetings.js

